name: ProxySpawn
version: 1.0.0
api-version: 1.21
main: net.rk4.proxyspawn.ProxySpawn
author: Lars
description: Proxy-compatible fixed spawn point plugin.
commands:
  pspawn:
    description: set a spawn point.
    usage: /<command>
